name: google_maps_cluster_manager
description: Simple Flutter clustering library for Google Maps based on Geohash.
version: 1.0.0
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  platform_maps_flutter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


